---
title: "Slides"
author: "Dr. Yue Hu"
output: html_document
---

This website collects a selected list of the slides of my public speeches. 
If you want to know more about me, welcome to my [personal page](https://sammo3182.github.io).

此页面汇集了我部分公开发言的相关资料。
如果您希望对其中某些研究有更深了解，请浏览我的[个人网页](https://sammo3182.github.io)查询更多内容或直接与我取得联系。    

#### Class slides 课件

+ <a href="/slides_gh/slides/courses/analysisOfPoliticalData/index.html">Analysis of Political Data (70700173)</a>
+ <a href="/slides_gh/slides/courses/governmentalBigData/index.html">Big Data Analysis for Governance (80700673)</a>
+ <a href="/slides_gh/slides/courses/analysisOfPublicPolicy/index.html">Analysis of Public Policy: Perspectives and Methods (30700953)</a>
+ <a href="/slides_gh/slides/courses/understandingPolicy/index.html">Understanding Policies: Interdisciplinary Perspectives and Case Illustrations (10700193)</a>
+ <a href="/slides_gh/slides/courses/dgpWorkshop/index.html">Data Collection Workshop</a>
+ <a href="/slides_gh/slides/courses/camsTextAnalysis/index.html">CAMS Course: Quantitative Text Analysis</a>
+ <a href="/slides_gh/slides/guestLecture/politicalCulture.html">Intro to Political Culture</a>


+ [Dr Hu's R Workshop Series](slides/courses/rWorkshop/)
+ <a href="/slides_gh/slides/courses/mathCamp/mathcamp.html">Math Basics for Poli Sci Students</a>
+ <a href="/slides_gh/slides/courses/teachingDemo/languagePolicy.html">Asian Politics: Language Policy</a>
+ <a href="/slides_gh/slides/courses/teachingDemo/languagePolicy_cn.html">亚洲语言政策</a> 

#### Guest Lecture 特邀讲座

- <a href="/slides_gh/slides/guestLecture/gateway.html"> 从学生到学者：基于三个理论和两条指示的一些个人意见</a>

* <a href="/slides_gh/slides/conference/2020-XinruiForum/inequalityChina.html"> Why Economic Inequality Undermines Political Trust</a>

* <a href="/slides_gh/slides/guestLecture/cssThoughts.html"> 计算·社会科学</a>

* <a href="/slides_gh/slides/guestLecture/efficacy.html"> Efficacy and Response to Response</a>

* <a href="/slides_gh/slides/guestLecture/effectivelyWriting_English.html"> 英文学术写作经验</a>

* <a href="/slides_gh/slides/guestLecture/surveyMethod.html"> 以科学方法探知民心</a>

* <a href="/slides_gh/slides/guestLecture/memory.html">Active Audience of Memory: How Past Collective Wins Change Present Political Judgements</a>(<a href="/slides_gh/slides/guestLecture/memory_domestic.html">中文</a>)

* <a href="/slides_gh/slides/courses/governmentalBigData/06_textAnalaysis.html">以数知文：计算机辅助内容分析原理与路径</a>

* <a href="/slides_gh/slides/conference/2021-SPSA/ciClosure.html">Resistance and Resilience</a>

* <a href="/slides_gh/slides/conference/2021-SPSA/secondHand.html">Second-Hand Data, First-Hand Design</a>

* <a href="/slides_gh/slides/guestLecture/intro2ScientificResearch.html">Introduction to Social Science Research</a>

* <a href="/slides_gh/slides/guestLecture/authorityMarker_long.html"> Cultural Marker vs. Authority Marker</a> 

* <a href="/slides_gh/slides/guestLecture/migrantDecision_hukou.html">Does Governmental Policy Shape Migration Decisions?</a>

* <a href="/slides_gh/slides/guestLecture/dcpo.html">Cross-Survey Analysis and Dynamic Comparative Public Opinion</a> (<a href="/slides_gh/slides/guestLecture/dcpo_s.html">brief</a>, <a href="/slides_gh/slides/guestLecture/dcpo_cn.html">中文</a>, <a href="/slides_gh/slides/guestLecture/dcpo_scn.html">惊鸿</a>)

* <a href="/slides_gh/slides/guestLecture/democracyDiscourse.html">中国政治语言中的民主概念</a>

* <a href="/slides_gh/slides/guestLecture/experiment.html">实验政治学的“能·好·怎”</a>
    - <a href="/slides_gh/slides/guestLecture/experiment_s.html">社会科学实验研究方法: 从原理到实践</a>

* <a href="/slides_gh/slides/guestLecture/patriotic_bases.html">展览馆里的政治传播</a>

* <a href="/slides_gh/slides/guestLecture/latentVariable.html">潜变量分析与诊断</a>


#### Conference Presentation 会议

+ <a href="/slides_gh/slides/conference/taiwan.html">2023 中流文教基金会两岸学术论坛: Who cares about Taiwan</a>

+ <a href="/slides_gh/slides/conference/psm_peer.html">2023 APSA: Beyond Righteousness</a>

+ <a href="/slides_gh/slides/conference/migrantCriminal.html">2023南京大学“政治文化、心理与行为研究”工作坊: 约束与包容</a>

+ <a href="/slides_gh/slides/conference/migrantCriminal.html">2023北大国发院法律政治经济学工作坊：基于大数据的司法治理研究</a>

+ <a href="/slides_gh/slides/conference/myMethod.html">2023吉林大学政治学一流学科建设论坛</a>

+ <a href="/slides_gh/slides/conference/identity_assessor.html">2023 北京青年政治学论坛: Leaders on Court</a>

+ <a href="/slides_gh/slides/conference/efficacy.html">2023 第五届政治传播研究学术论坛: Efficacy and Response to Response</a>

+ <a href="/slides_gh/slides/conference/memory.html">2023 MPSA: Active Audience of Memory</a>

* <a href="/slides_gh/slides/conference/psm_policy.html"> 2022中国青年政治学论坛: 公共服务动机激发机制的实验研究</a>

* <a href="/slides_gh/slides/conference/identity_assessor.html"> 2022 Xinrui Forum: Identity Politics in Chinese Courts</a>

* <a href="/slides_gh/slides/conference/ope.html"> 2022 MPSA: How Political Experience Shapes Online Political Efficacy and Participation Cognition</a>

* <a href="/slides_gh/slides/conference/democracyDiscourse_en.html"> 2021 Cultural and Social Computing Lectures</a>

* <a href="/slides_gh/slides/conference/inequalityTrust_cn.html"> 2021 文心清华•黄岩讲坛暨: How Inequality Affects Political Trust: A Mediation Analysis</a>

* <a href="/slides_gh/slides/conference/ciClosure.html"> 2021 SPSA: Resistance and Resilience</a>

* <a href="/slides_gh/slides/conference/languageTrust.html"> 2021 IPSA: Linguistic Relativity of Political Trust</a>

* <a href="/slides_gh/slides/conference/languageEnglish.html"> 2021年政治学与国际关系学术共同体年会: 语言政治场域</a>

* <a href="/slides_gh/slides/conference/diverseLoyalty.html"> 2021 中国政治传播研究学术论坛: Diverse Loyalty</a>

* <a href="/slides_gh/slides/conference/dcpoDemo.html"> 2021 AsianPolmeth VIII & ASQPS IXs: DCPO</a>

* <a href="/slides_gh/slides/conference/fandom.html"> 2020 中国心理学会文化心理学专业委员会学术年会: 青少年饭圈身份认同与公共参与</a>

* <a href="/slides_gh/slides/conference/inequalityTrust.html"> 2020 第一届中国政治新锐研究研讨会: How Inequality Affects Political Trust: A Mediation Analysis</a>

* <a href="/slides_gh/slides/conference/languageGovernance.html"> 2019 第六届政治科学与方法: 新型城镇化中的语言治理</a>

* <a href="/slides_gh/slides/conference/migrant_hukou.html">2019 计算社会科学国际学术会议: How Does Governmental Policy Shape Migration Decisions?</a>

* <a href="/slides_gh/slides/conference/dotwhisker-interplot.html">2019 R China Conference</a>

* <a href="/slides_gh/slides/conference/democracyDiscourse_en.html">2019 Fudan-Tsinghua Workshop: Strategic Communication</a>

* <a href="/slides_gh/slides/conference/proficiencyTrust.html">2018 MPSA: Rebuilding the Tower of Babel</a>

* <a href="/slides_gh/slides/jobtalk/authorityMarker.html"> 2018 MPSA: Cultural Marker vs. Authority Marker</a> 

* <a href="/slides_gh/slides/conference/migrant_language.html">2019 ACPS: Breaking through the Barrier</a>

#### Reports 报告

+ <a href="/slides_gh/slides/report/index.html"> List of Reports








