---
title: "Slides"
author: "Dr. Yue Hu"
output: html_document
---

This website collects a selected list of the slides of my public speeches. 
If you want to know more about me, welcome to my [personal page](https://www.drhuyue.site).

此页面汇集了我部分公开发言的相关资料。
如果您希望对其中某些研究有更深了解，请浏览我的[个人网页](https://www.drhuyue.site)查询更多内容或直接与我取得联系。    


#### Class slides 课件

- [Analysis of Political Data (70700173)](/slides/courses/analysisOfPoliticalData/index.html)
- [Big Data Analysis for Governance (80700673)](/slides/courses/governmentalBigData/index.html)
    - [CAMS Course: Quantitative Text Analysis](/slides/courses/camsTextAnalysis/index.html)
- [Analysis of Public Policy: Perspectives and Methods (30700953)](/slides/courses/analysisOfPublicPolicy/index.html)
    - [Data Collection Workshop](/slides/courses/dgpWorkshop/index.html)
- [Understanding Policies: Interdisciplinary Perspectives and Case Illustrations (10700193)](/slides/courses/understandPolicy/index.html)
- [Professionalism & Competence in Social Science (70700511)](/slides/courses/professionalism)
- [Learning R with Dr. Hu & His Friends](slides/courses/rWorkshop/)
    - [Math Basics for Poli Sci Students](/slides/courses/mathCamp/mathcamp.html)
- [Intro to Political Psychology](/slides/courses/politicalPsychology/index.html)
- [Intro to Political Culture](/slides/guestLecture/politicalCulture.html)
- [国际关系理论研讨班](/slides/guestLecture/softPower.html)
- [教研院：中国概况](/slides/courses/chinaPerspective/democraticSupport.html)
- [Asian Politics: Language Policy](/slides/courses/teachingDemo/languagePolicy.html)
- [亚洲语言政策](/slides/courses/teachingDemo/languagePolicy_cn.html) 

#### Invited Talks 特邀讲座

- [2025 文化心理学研究中心国际暑期学校: Perceiving Economic Inequality](/slides/guestLecture/inequality_perceiving.html)
- [2025 中国人民大学新闻学院博士生写作课程](/slides/guestLecture/effectivelyWriting_English.html)
- [2025 清华基层社会治理研究中心系列讲座: Personality and Civic Quality](/slides/guestLecture/language_tw.html)
- [2025 华南师大：砚湖政管青年论坛第三期](/slides/conference/language_publicServant.html)
- [2025 HKU: Personality and Civic Quality in the Online Society](/slides/guestLecture/language_tw.html)
- [2024 清华大学：清华大学新闻与传播前沿讲座](/slides/guestLecture/weibo.html)
- [2024 中国农业大学：社会科学实验研究方法: 从原理到实践](/slides/guestLecture/experiment_s.html)
- [2024 山西大学邓初民讲堂：Why Economic Inequality Undermines Political Trust](/slides/conference/inequalityChina.html)
- 兰州大学鹿鸣讲堂两场
    - [2024-07-17 远读：文本的数据分析原则与应用](/slides/courses/governmentalBigData/06_textAnalysis.html)
    - [2024-07-18 英文学术写作](/slides/guestLecture/effectivelyWriting_English.html)
- [中国政法大学：英文学术写作](/slides/guestLecture/effectivelyWriting_English.html)
- [深圳大学：以数知文](/slides/courses/governmentalBigData/06_textAnalysis.html)
- [清华大学社科学院教师学术报告会：以语塑心与认知治理](/slides/guestLecture/officialLanguageField_cn.html)
- [复旦大学士派工作坊：官方语言场域](/slides/guestLecture/officialLanguageField_cn.html)
- [南京大学政治学研究工作坊：Why materializing patriotism](/slides/guestLecture/patrioticBases.html)
- [University of Macau: Official Language Shapes Political Minds?](/slides/guestLecture/officialLanguageField.html)
    - [Example of Causal Inference](/slides/guestLecture/corruption_grassroot_en.html)
- [南京师范大学“论道·名家讲坛”：语言政策的认知治理效能与机制研究](/slides/guestLecture/officialLanguageField.html)
- [山东大学“政治学新锐讲座”: Beyond Righteousness](/slides/guestLecture/psm_peer_long.html)
- [广州大学“南国讲堂”：社会科学实验研究方法: 从原理到实践](/slides/guestLecture/experiment_s.html)
- [华南师范大学：Who Is Watching Xinwen Lianbo and Why](/slides/guestLecture/cctvAudience.html)
- [从学生到学者：基于三个理论和两条指示的一些个人意见](/slides/guestLecture/gateway.html)
- [Why Economic Inequality Undermines Political Trust](/slides/conference/inequalityChina.html)
- [复旦大学：社会科学实验研究方法: 从原理到实践](/slides/guestLecture/experiment_s.html)
- [计算·社会科学](/slides/guestLecture/cssThoughts.html)
- [Efficacy and Response to Response](/slides/guestLecture/efficacy.html)
- [英文学术写作经验](/slides/guestLecture/effectivelyWriting_English.html)
- [以科学方法探知民心](/slides/guestLecture/surveyMethod.html)
- [Active Audience of Memory: How Past Collective Wins Change Present Political Judgements](/slides/guestLecture/memory.html)
- [Resistance and Resilience](/slides/conference/2021-SPSA/ciClosure.html)
- [Second-Hand Data, First-Hand Design](/slides/conference/2021-SPSA/secondHand.html)
- [Introduction to Social Science Research](/slides/guestLecture/intro2ScientificResearch.html)
- [Cultural Marker vs. Authority Marker](/slides/guestLecture/authorityMarker_long.html)
- [Does Governmental Policy Shape Migration Decisions?](/slides/guestLecture/migrantDecision_hukou.html)
- [Cross-Survey Analysis and Dynamic Comparative Public Opinion](/slides/guestLecture/dcpo.html)
- [中国政治语言中的民主概念](/slides/guestLecture/democracyDiscourse.html)
- [中国农业大学：实验政治学的“能·好·怎”](/slides/guestLecture/experiment.html)
- [展览馆里的政治传播](/slides/guestLecture/patriotic_bases.html)
- [潜变量分析与诊断](/slides/guestLecture/latentVariable.html)

#### Conference Presentation 会议

- [2025 云南大学：政治认知的语言效应与机制](/slides/conference/language_field_cn.html)
- [2025 山西大学：纪念邓初民](/slides/conference/corruption_outcome.html)
- [2025 人民大学：新闻传播学定量研究方法研讨会](/slides/conference/llm_thoughts.html)
- [2025 PS symposium: Data Wrangling](/slides/conference/dcpo_wrangle.html)
- [2025 云南大学：Leverage or Burden](/slides/conference/memory.html)
- [2025 南师大：数字时代的公共治理](/slides/conference/language_publicServant.html)
- [2025 第三届计算社会科学国际会议](/slides/conference/language_publicServant.html)
- [2024 第九届跨代对话会](/slides/conference/language_publicServant.html)
- [2024 北京外国语大学第四届比较政治学论坛](/slides/conference/cpChina.html)
- [2024 新锐论坛](/slides/conference/patrioticBases_short.html)
- [2024 APSA](/slides/conference/inequality_compare.html)
- [2024 清华大学：第一届计算政治学会议](/slides/conference/languageTW.html)
- [2024 清华大学：第二届清华大学-中流文教基金会两岸学术研讨会](/slides/conference/languageTW.html)
- [2024 南京大学：第十二届“政治文化、心理与行为研究”工作坊](/slides/conference/languageTW.html)
- [2024 清华大学：《政治学研究》华北地区中青年作者座谈会](https://drhuyue.site:10002/sammo3182/miscellaneous/honorInstitution.pptx)
- [2024 吉林大学：第十四届比较政治学论坛](/slides/conference/macrointerest.html)
- [2024 港中深：2024 International Conference on China's Development and Governance at 75](/slides/conference/macrointerest.html)
- [2024 “迈向自主知识体系的中国式现代化”理论研讨会](/slides/conference/myMethod.html)
- [2024 第六届中国政治传播研究学术论坛: Strait Watcher Behind the Screen](/slides/conference/languageTW.html)
- [2024 第七届政治学与国际关系教学共同体年会：新文科人才培养目标、挑战与尝试](/slides/conference/newLA.html)
- [2023 清华大学政治学系第八届跨代对话：民主与民意](/slides/conference/dcpo.html)
- [2023 第九届政治研究前沿论坛：How Past Win Affects Today's Fight](/slides/conference/memory.html)
- [2023 第五届计算社会科学高端论坛: Leaders on Court](/slides/conference/identity_assessor.html)
- [2023 第三届廉政与治理工作坊：基层非正规经济行为感知现状及其影响](/slides/conference/corruption_outcome.html)
- [2023 城市治理与政治发展会议：基层腐败治理的民心导向与结构差异](/slides/conference/corruption_grassroot.html)
- [2023 政治心理理论与方法学术研讨会：How Past Win Affects Today's Fight](/slides/conference/memory.html)
- [2023 行为公共管理前沿研究工作坊: Beyond Righteousness](/slides/conference/psm_peer.html)
- [2023 中流文教基金会两岸学术论坛: Who cares about Taiwan](/slides/conference/taiwan.html)
- [2023 APSA: Beyond Righteousness](/slides/conference/psm_peer.html)
- [2023南京大学“政治文化、心理与行为研究”工作坊: 约束与包容](/slides/conference/migrantCriminal.html)
- [2023北大国发院法律政治经济学工作坊：基于大数据的司法治理研究](/slides/conference/migrantCriminal.html)
- [2023吉林大学政治学一流学科建设论坛](/slides/conference/myMethod.html)
- [2023 北京青年政治学论坛: Leaders on Court](/slides/conference/identity_assessor.html)
- [2023 第五届政治传播研究学术论坛: Efficacy and Response to Response](/slides/conference/efficacy.html)
- [2023 MPSA: Active Audience of Memory](/slides/conference/memory.html)
- [2022中国青年政治学论坛: 公共服务动机激发机制的实验研究](/slides/conference/psm_policy.html)
- [2022 Xinrui Forum: Identity Politics in Chinese Courts](/slides/conference/identity_assessor.html)
- [2022 MPSA: How Political Experience Shapes Online Political Efficacy and Participation Cognition](/slides/conference/ope.html)
- [2021 Cultural and Social Computing Lectures](/slides/conference/democracyDiscourse_en.html)
- [2021 文心清华•黄岩讲坛暨: How Inequality Affects Political Trust: A Mediation Analysis](/slides/conference/inequalityTrust_cn.html)
- [2021 SPSA: Resistance and Resilience](/slides/conference/ciClosure.html)
- [2021 IPSA: Linguistic Relativity of Political Trust](/slides/conference/languageTrust.html)
- [2021年政治学与国际关系学术共同体年会: 语言政治场域](/slides/conference/languageEnglish.html)
- [2021 中国政治传播研究学术论坛: Diverse Loyalty](/slides/conference/diverseLoyalty.html)
- [2021 AsianPolmeth VIII & ASQPS IXs: DCPO](/slides/conference/dcpoDemo.html)
- [2020 中国心理学会文化心理学专业委员会学术年会: 青少年饭圈身份认同与公共参与](/slides/conference/fandom.html)
- [2020 第一届中国政治新锐研究研讨会: How Inequality Affects Political Trust: A Mediation Analysis](/slides/conference/inequalityTrust.html)
- [2019 第六届政治科学与方法: 新型城镇化中的语言治理](/slides/conference/languageGovernance.html)
- [2019 计算社会科学国际学术会议: How Does Governmental Policy Shape Migration Decisions?](/slides/conference/migrant_hukou.html)
- [2019 R China Conference](/slides/conference/dotwhisker-interplot.html)
- [2019 Fudan-Tsinghua Workshop: Strategic Communication](/slides/conference/democracyDiscourse_en.html)
- [2019 ACPS: Breaking through the Barrier](/slides/conference/migrant_language.html)
- [2018 MPSA: Rebuilding the Tower of Babel](/slides/conference/proficiencyTrust.html)
- [2018 MPSA: Cultural Marker vs. Authority Marker](/slides/conference/authorityMarker.html)


#### Reports 报告

- [List of Reports](/slides/report/index.html)








