---
title: '香港群体身份认同的互动塑造机制研究'
subtitle: '2020年度清华大学国家高端智库自主立项课题'
author: "胡悦"

# date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    self_contained: FALSE
    chakra: libs/remark-latest.min.js
    css: 
      - default
      - zh-CN_custom.css
      - style_ui.css
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    nature:
      highlightStyle: github
      highlightLines: true
      highlightSpans: true
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, htmltools.dir.version = FALSE)

xaringanExtra::use_xaringan_extra(c("tile_view", 
                                    "broadcast", 
                                    "panelset",
                                    "tachyons"))


library(pacman)

p_load(icons)

# Functions preload
set.seed(313)
```


class: center, middle, normal

## 摘要

**核心指向**

深挖香港政治经济不稳定.red[根源]，维护香港.red[长治久安]
+ 理解香港问题社会经济根源
+ “一国”框架下，引导身份认同良性建构
+ “两制”条件下，促进协同发展

**解题方法**

以.red[群体]身份认同切口
+ 代表性全港调查 + 批量媒体文本 + 深度访谈
+ 大数据与小数据结合、定量与定性方法结合

---

class: normal

## 研究成果

+ 身份认同的内在危机    
+ 身份认同的外部塑造    
+ 内外互动塑造机制    

.large[&dArr;]

《香港群体身份认同的互动塑造机制研究》

1. 《香港群体身份认同现状——“反修例”事件前夕港人政治心态初探》
1. 《香港与内地群体身份认同之互动机制研究》

---

## 香港群体身份认同现状

数据：2016年全港代表性数据

发现：

1. 整体性悲观： 超过一半的受访者认为回归后香港的整体发展情况“倒退了”，仅有2成左右受访者认为“进步了”。

图2： 各年龄层人群占比均衡，青年群体比例较高。同样地，在认为“悲观”的群体中，最多占比则为高学历人士（大专或以上），而且比例远高于其他组别。

1. 是学生还是学生家长：图1
    + “倒退了”的群体中，各年龄层人群占比均衡，中年群体比例较高；高知比例高
    + 认同香港回归后整体发展情况比回归前更进步了的群体当中，占比最多的反而是青年人

1. 悲观植根于发展
    + 并非单纯来自于香港回归以来发展的情况
    + 42%市民对于未来五年香港的经济发展表示“信心不大”和“没有信心”

1. “港独”动力：四分之一受访者认为主张港独的团体成立目的在于“维护香港利益”
    + 最多为中年、青年群体，占比分别为41%和42%
    + 低收入群体的港独倾向更加明显
    + 对此表示“无意见”的人群当中，最多占比的反而也是青年
    + 高知支持更多
    + 最多占比者为高学历人士，比例高达43.3%且远高于其他学历背景人群。有意思的是，在认为是为了“获取个人利益”的人群当中，多达83.3%“拒答”，拒绝透露其教育背景

总结：

+ 香港问题是群体身份认同危机的集中体现，而不仅仅是国家认同问题；
+ 香港动乱的根源在于香港市民对香港现状和未来发展缺乏信心，市民悲观情绪有两极化趋势；
+ 香港问题是全港性的，且在各市民群体中的特征是异质性的。

---

## 外部因素：内地人香港观

---

## 香港与内地群体身份认同互动塑造

---

## 政策建议

---

class: inverse, center, middle

# Thanks

`r feather_icons("mail")`&nbsp;[yuehu@tsinghua.edu.cn](mailto:yuehu@tsinghua.edu.cn) 

`r feather_icons("globe")`&nbsp; https://sammo3182.github.io/

`r feather_icons("github")`&nbsp; [sammo3182](https://github.com/sammo3182)

