---
title: "Reports"
author: "Dr. Yue Hu"
output: html_document
---

This website collects a selected list of the slides of my reports for academic and administrative sake. 
If you want to know more about me, welcome to my [personal page](https://sammo3182.github.io).

此页面汇集了我部分报告的相关资料。
如果您希望对其中某些研究有更深了解，请浏览我的[个人网页](https://sammo3182.github.io)查询更多内容或直接与我取得联系。    

### Defense

#### Tenure

- [职务晋升：长聘副教授](tenure_associate.html)
- [职务晋升：准聘副教授](tenureTrackAP.html)
- [Job Talk：语言标记 vs. 权威标记](authorityMarker_cn.html)
- [Job Talk：Culture Marker vs. Authority Marker](authorityMarker.html)

#### Title

- [“学术新人奖”答辩汇报](newStar.html)
- [“学术新人奖”答辩汇报(使用版)](newStar.pptx)
- [2025 青年拔尖人才项目](qingba.html)

#### Project

- [国家智库：香港群体身份认同的互动塑造机制研究](hongkong.html)

### Miscellaneous

- [2025 世界一流智库建设国际考察](worldThinkTank.html)
- [2025 研究生教改立项论证交流会](ge_aiThesisCourse.html)
- [2024 优质通识课程建设计划(结项)](ge10min.html)
- [2023 务虚会个人介绍](individual.pptx)
- [2023 政治学类本科专业建设与人才培养研讨会](/slides/conference/2023-undergradEdu/undergradEdu.html)
- [2023 优质通识课程建设计划](ge5min.html)
- [2023 研究生教改答辩](graduateReform_2023S.html)
- [清华社科：顶尖大学与顶尖学者·政治科学](topScholars.html)
- [清华大学政治学系介绍](/slides/guestLecture/intro2tsinghuaPS.html)
- [政治学与行政学专业宣讲](/slides/guestLecture/intro2tsinghuaPS_college.html)
- [清华大学计算社会科学平台介绍](/slides/guestLecture/intro2CSS.html)
