---
title: "Draft for MPSA 2018"
output: word_document
---

Thank you for giving me this chance to present this interesting project. 
I would like to start my talk with an old, well-known biblical story: The Tower of Bable.
At the time people shared one language that everyone can understand each other.
They decided to build a tower to connect to the heaven, which made God feel his authority was threatened. 
To protect the authority, God messed up people's language.
Well, if you look at China, a totally different story is telling there.
What the Chinese government did in the past six decades was to encourage all the citizens to learn and use one single language, Putonghua.
Things become even more interesting if you look around the world and found China is not exceptional. 
France has done this.
German has done this. 
And so do many other countries, no matter democracies or autocracies.
Why do they follow the completely opposite logic to the biblical story?
Don't these governments afraid of their authority being threatened as God did in the story? 

I seek for the answer to these questions by investigating how language policy affects citizens' political attitudes and trust.
Although there have been some political science studies touching on this area  (mainly from ethnolinguistics), the existing research cannot sufficiently explain the relationship between language policy and political attitudes due to at least three limitations. 

First, a lion share of them focuses only on a small part of the population, such as ethnic minorities or immigrants.
Does language policy, the policy that determines the national primary language and the linguistic system of the entire country only influence these minorities?
Probably not.
In addition, many existing studies only focus on the influence of language policy during the state building phase investigating how it contributes to the domestic ethnic relations and the construction of the common imagination of citizens. 
But what happens after that phase? 
Will language policy lose its influence once people recognize them with the shared nationality? 
Finally, most existing literature focus on cultural competition, such as Latino vs. white and
Uyghur vs. Han. 
In these studies, language is regarded as nothing but a proxy of a specific culture and assume people's response to language policy just reflect their attitudes towards the culture.
I agree that language plays a crucial rule in constructing culture. 
However, symbolizing culture is not the primary function of language in our daily life.
Communication is.
In this sense, only focusing on culture may make us ignore some more general impact of language and language policy.

Therefore, the goal of this research is to build a theory that explains the impact of language policy on the full population with established social and political identities from a perspective beyond culture.
There is one thing, though, the new theory will share with the conventional ones, that is, focusing on the official language. 
Official language is the core of most language policies and the common reference for observing the influence of the policy on the entire country.

This theory argues that language policy can affect people's political attitudes and trust through the three general communication functions of official language: listening, speaking, and comparison.
First, official language is the unique language governments use to publish laws, policies, and express political wills.
For those who have a better listening comprehension, they are thus more likely to be exposed to the governmental propaganda more and thus be influenced by them more.
Correspondingly, thse people are expected to know the established system more and align more with the central government.
Be aware that aligning with the government doesn't mean blindly support the government.
Taking China as an example, as many recent studies have indicated, the Chinese central government has a strategy to distract the anger of the public from the central to the local.
In this sense, aligning with the government means acting exactly as the government plans.


Second, the official language is the dominant inter-communal language. 
Thus, people who speak the language well know that they have stronger capability to express their ideas and opinions, to more people, since they can be confident that others can understand you.
With this awareness and confidence, these well-speakers are more active in social and political expressions and participations.
I therefore expect them to have more interest and internal efficacy in politics. 
However, in a regime such as China where the institutional channel of political participation is not always guaranteed, more activism usually leads to more dissatisfaction.
"Hey, I express the idea reasonably and well! Why doesn't the government listen to me?!"
Right?
That will lead to less external efficacy and more negative impression of the officials.

Finally, I will introduce in a new perspective of official language proficiency. 
That is, the relative proficiency. 
A bunch of literature argues that a high official language proficiency will make an individual more competitive and access more sources for development.
I agree with this argument with a condition that the high proficiency should be a relative concept here. 
Taking my lovely wife as an example.
She was born in a dialect zone in China.
Although she has done her best to learn authentic Putonghua, I can still identify the dialect's influence on her.
So, if she lives in an environment where most people's speaking proficiency is as high as me, she won't be able to take any advantage from her Putonghua, despite her decent speaking proficiency.
However, if she back to her hometown where most people speak the dialect, her Putonghua proficiency will be outstanding there, and she may earn more chances and sources becaus of this advantages
In other words, you can take the advantage of official language without having a perfect speaking proficiency. 
You just need to be better than the people who live or work around.
And for these people who have a higher relative proficiency, they are more suitable for the society.
They can live better with the language advantages.
In turn, their self-evaluation is expected to be high.
So does their attachiment to the established political environment that favors them.
Their enthusiasm to change it, then, would be lower, and the trust in the established political system could be higher.

Ok, we have the theory now.
I test these inferences with the data from China.
In particular, I used the CGSS data, probably the best over-time nationwide representative survey data we have now. 
It started to ask questions about Putonghua proficiency since 2010, and I use all the available data since then.

To conduct a thorough and robust test, I tested the hypotheses I showed you with sixteen dependent variables.
Due to the time limit, I can't go through them one by one. 
So for now, let's focus on the most interesting part: political trust. 
They are measured in four aspects: the trust in the legislature, central and local governments, and judicial system. 

The independent variables include three types of Putonghua proficiency.
Two of them were directly from the survey question.
The relative proficiency was measured by the difference between the respondent's speaking proficiency and the average proficiency of his or her county. 
Apart from this, I also added a battery of controls of respondents' demographic and socioeconomic characteristics.
A regional fixed effect model is applied to control for the unobservable spatial variance. 
So do the post-stratification weights.
If multiple waves of data were used together, wave binaries were also included.

Let's have a look at the results.
In this dot-whisker plot, each panel represents a model. 
The controls are omitted in the interest of space.
The dots are coefficients, and the whiskers are 95% confidence intervals.
Let's look at listening proficiency. 
We have positively significant results on both legislature and central government and negatively significant result on local government. 
The effect on the judiciary that is rarely mentioned in the political propaganda is insignificant. 
The results follow the government pretty well, aren't they!
Then let's look at the speaking and relative proficiencies. 
Speaking: significantly negative all over the models except for the local government.
People trust the established regime less when they speak the official language well.
Relative is the opposite: significantly positive across the models. 
Those who can take the advantage from language trust the established institution more.
Besides these, the rest twelve models I didn't show here also support the hypotheses of the communication-based theory.
I have them here in the appendix, but I just don't have time to show you.
We can talk about them in Q&A, though, if you are interested.

So, I consider all these results together provide strong and robust evidence for the mechanism and outcome of the communication-based theory.
And it should be sufficient to answer the question why a large number of governments prefer rebuilding the Tower of Babel. 
It could benefit the political support through multiple ways.
More importantly, this research provides a general communication-based theory that goes beyond any specific culture to understand the influence of language policy.
The theory can be easily applied in other countries, although the inferences might be different according to the concrete states.
The theory also provides a new insight into the political influence of language policy apart from ethnic balancing and state building.
Finally, it uncovers a factor that can significantly affect public opinion that has been long neglected.
This could also be a new window for us to understand the government-citizen communications.
For instance, we all knew the strategy of the Chinese government on central and local government trust, and we do see Chinese citizens' trust are different at the two levels. 
However, the citizens could be just like this all the time---trust the central more than the local, even without the strategic guide.
This research, however, provides evidence that government's strategy does shape people's opinions.
