---
title: "Defense Draft"
output: word_document
---

My research question derives from a comparison of two types of logic applied by a biblical and a secular authority. 
In the story of Tower of Babel, God stopped the project to protect his authority. 
The way he did it was messing up the human language so that they cannot communicate with each other.
It is interesting to compare this with what the Chinese government, a secular authority, did during over half a century. 
In the past six decades, the Chinese government has consistently promoted a language policy to push all the citizens to learn and use one single language, Putonghua.
As presented in the scroll, "Everybody should speak Putonghua." 
Things become even more interesting if you look around the world and found China is not exceptional. 
France has done this.
German has done this. 
And so do many other countries, no matter democracies or autocracies.
Why do they follow the completely opposite logic to the biblical story?
Aren't they afraid of their authority being threatened? 

I seek for the answer to these questions by investigating how language policy affects citizens' political attitudes and trust.
Although there have been some political science studies touching on this area, they are insufficient to answer our question because of at least three limitations.

First, most of them focus only on a small part of the population, such as ethnic minorities or immigrants.
Or they will only focus on the influence of language policy during the state building phase investigating how it contributes to the domestic ethnic relations and the construction of the common imagination of citizens.
Finally, most existing literature regard language as nothing but a proxy of a specific culture and assume people's response to language policy just reflect their attitudes towards the culture.
I agree that language plays a crucial rule in constructing culture. 
However, identifying culture is not the only or even primary function of language in our daily life.

Therefore, the contribution of my research is to provide a theory that explains the impact of language policy on the full population with established social and political identities from a perspective beyond culture.
There is one thing, though, I share with the conventional ones, that is, focusing on the official language. 
Official language is the core of most language policies and the common reference for observing the influence of the policy on the entire country.

The new theory is thus also named after it, the official language field theory, or the OLF theory.
The theory argues that language policy does not target a certain group or certain phase of state development.
Instead, it influences as a magnetic field. 
As the magnetic field pulling nails towards the magnet, the official language field pulls official language speakers towards the government, although not their physic bodies but mind.
In particular, the theory specifies unique mechanisms that citizens' attitudes towards the government, relationship with the government representatives, and political value are influenced by the official language field and reflected in the institutional, process, and concept-based trust. 

My research conducts a comprehensive and systematic examination of the OLF theory through testing the consequences of its status and corpus planning on these three aspects with multiple sources from different aspects of official language.
The main data source comes from China.
The case is selected because its unique condition that its linguistic and cultural distributions are not entirely overlapped.
So, I can distinguish the language policy influence from cultural influence.

Here's the summary of the findings. 
The research found that people's political trust is significantly influenced by the official language field through three paths.
In terms of general political attitudes and self-evaluation, although higher speaking proficiency of official language leads to more political activism and doubt of the government, listening and relative proficiency (that is, how is your speaking proficiency in comparison with others) provide a salient effect on institutional-based trust. 
In terms of the relationship with the government representatives, using official language can produce more trust in the conversation partner, while this effect works only when the speaker has a political identity as the representative of the government.
Finally, in terms of political value, I found a strategy of the government to manipulate political concepts both on their definition and relationship with other concepts, with an example of "democracy."

I believe these findings can have far-reaching implications in both language policy study and comparative politics.
For language policy study, it provides a more general theory that can be used to explain and compare policy effects beyond cultural boundaries. 
It responds to the existing literature from ethnolinguistics and post-modernization theory that language policy's influence is far more broad and profound than balancing ethnic relations or constructing imagined communities.
The research also provides a new perspective for policymakers to decide what language policy they should adopt.

From a broader view of comparative politics, while the existing literature is used to talk about how social and political identity affects a state's policy, this research shows a backward process that how political policy shapes people's identity and attitudinal patterns.
Second, the research also opens a new winder to understand the government-citizen communication.
For instance, in one of the chapters I mentioned a growing literature about the Chinese government's strategy to distract public anger from the central to the local governments.
The studies have shown that the government is applying this strategy and that citizen show a consistent pattern in their attitudes towards the government.
However, correlation is not causality.
How do we know the attitudinal patterns of public opinion result from government's efforts?
Maybe the citizens just regard the central and local government in such way even the government does nothing.
The finding of my research, though, shows the relationship between the consequence of government's policy efforts, that is, people's official language proficiencies and their political trust, which may help us to confirm the government's influence on citizens.

