---
title: "Association Analysis"
subtitle: "Analysis of Political Data (70700173)"
author: "Yue Hu"
institute: "Political Science, Tsinghua University"
# date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: 
      - ../../../css/zh-CN_custom.css
      - ../../../css/styles.css
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    chakra: ../../../libs/remark-latest.min.js # to show slides offline
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)


if (!require(pacman)) install.packages("pacman")
library(pacman)

p_load(
  flextable,
  knitr, # dependency
  descr, stringr, broom, tidyverse
) # data wrangling # data wrangling

# Functions preload
set.seed(114)
```


class: inverse, bottom

# Association

---

## Joint Distribution Revisit 

What's joint distribution in the probability theory? 

--

$$n_{\bullet\bullet} = \sum\sum n_{ij}.$$

--

In statistics, joint distribution refers to the joint patterns of two or more variables. 

---

## Covariance: 

$$\sigma_{X, Y} = \sum(X - \mu_x)(Y - \mu_y)p(x,y)$$.

---

class: small

e.g., n: population 10,000,000, X: education, Y: age, 

| Education 	| 20~35 (mean = 30) 	| 35~55 (mean = 45) 	| 55~100 (mean = 70) 	|
|-----------	|----------------	|----------------	|-----------------	|
| 0         	| 1000000        	| 2000000        	| 5000000         	|
| 1         	| 3000000        	| 6000000        	| 10000000        	|
| 2         	| 18000000       	| 21000000       	| 15000000        	|
| 3         	| 7000000        	| 8000000        	| 4000000         	|

--

\begin{align}
\mu_X =& \sum Xp(x) \\
      =& 0 * 0.8 + 1 * 0.19 + 2 * 0.54 + 3 * 0.19 = 1.84;\\
\mu_Y =& 30 * 0.29 + 45 * 0.57 + 70 * 0.34 = 49.15.\\
\sigma_{x, y} =& (0 - 1.84)(30 - 49.15)* 0.01 \\
               & + (0 - 1.84)(45 - 49.15)*0.02\dots = -3.636
\end{align}

---

## Correlation

For a population:

$$\rho_{X,Y} = \frac{\sum(X - \mu_X)(Y - \mu_Y)p(x,y)}{\sqrt{\sum(X - \mu_X)^2p(X)}\sqrt{\sum(Y - \mu_Y)^2p(Y)}}$$

For a sample: 

$r_{XY}=\frac{\sum_{i=1}^n (x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum_{i=1}^n(x_i-\bar{x})^2}\sqrt{\sum_{i=1}^n(y_i-\bar{y})^2}}.$


Relations with covariance: $\rho_{X,Y} = \frac{\sigma_{X, Y}}{\sigma_X\sigma_Y}$

---

class: small

## Correlations

### Pearson's r

$$\rho_{X,Y} = \frac{\sum(X - \mu_X)(Y - \mu_Y)p(x,y)}{\sqrt{\sum(X - \mu_X)^2p(X)}\sqrt{\sum(Y - \mu_Y)^2p(Y)}}$$

For a sample: 

$$r_{XY}=\frac{\sum_{i=1}^n (x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum_{i=1}^n(x_i-\bar{x})^2}\sqrt{\sum_{i=1}^n(y_i-\bar{y})^2}}.$$

Properties： 

1. $\rho_{XY}\in [-1,1]$, independent 0.
1. Greater value indicates stronger linear relationship.
1. Parametric test (a.k.a., assuming normal distribution, linearity, and homoscedasticity.)
1. Not robust to skewed data and outliers.

---

.red[ASSUMPTION]

1. Continuous data
1. Linear Relationship

???

https://statistics.laerd.com/spss-tutorials/pearsons-product-moment-correlation-using-spss-statistics.php

---

### Kendall's &tau;

For any pair of observations $x_{i},y_{i}$ and $x_{j},y_{j}$, where $i<j$: 

**Concordant pairs**: , if both $x_{i}>x_{j}$ and $y_{i}>y_{j}$; or if both $x_{i}<x_{j}$ and $y_{i}<y_{j}$. 

**Discordant pairs**:  if $x_{i}>x_{j}$ and $y_{i}<y_{j}$; or if $x_{i}<x_{j}$ and $y_{i}>y_{j}$. 

**Tied pairs**: If $x_{i}=x_{j}$ or $y_{i}=y_{j}$, the pair is neither concordant nor discordant.

---

$$\tau=\frac{n_c-n_d}{n_c+n_d}=\frac{n_c-n_d}{\binom{n}{2}}$$

* $n_c$: concordant pair.
* $n_d$: discordant pair.

--

Properties：

1. $\tau_{XY}\in [-1,1]$, independent 0.
1. Non-parametric test.

---

.red[ASSUMPTION]

???

https://statistics.laerd.com/spss-tutorials/kendalls-tau-b-using-spss-statistics.php

---

class: small

### Spearman &rho;

* Another ranking correlation 
* Non-parametric version of Pearson R

$$\rho _{\operatorname {rg} _{X},\operatorname {rg} _{Y}}={\frac {\operatorname {cov} (\operatorname {rg} _{X},\operatorname {rg} _{Y})}{\sigma _{\operatorname {rg} _{X}}\sigma _{\operatorname {rg} _{Y}}}}$$

$rg$: The rank of the variable

When all n ranks are distinct integers:

$$\rho_{s}={1-{\frac {6\sum d_{i}^{2}}{n(n^{2}-1)}}}$$

$d_{i}=\operatorname {rg} (X_{i})-\operatorname {rg} (Y_{i})$

???

https://statistics.laerd.com/statistical-guides/spearmans-rank-order-correlation-statistical-guide.php

---

## Pearson's r vs. Spearman's &rho;

Non-parametric, therefore, useful when Assumption 1 of Pearson's r is violated.
    
Pearson's r: Linear relationship
Spearman's &rho;: monotonic relationship

Kendall's &tau; and Spearman's &rho; can be used for ordinal variables.

---

